// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json_serializable_twin_rust_async.freezed.dart';
part 'json_serializable_twin_rust_async.g.dart';

@freezed
class StructForJsonSerializableTwinRustAsync
    with _$StructForJsonSerializableTwinRustAsync {
  const StructForJsonSerializableTwinRustAsync._();
  const factory StructForJsonSerializableTwinRustAsync({
    required String name,
    required int age,
  }) = _StructForJsonSerializableTwinRustAsync;
  Future<String> detailsTwinRustAsync() => RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinRustAsyncStructForJsonSerializableTwinRustAsyncDetailsTwinRustAsync(
        that: this,
      );

  static Future<StructForJsonSerializableTwinRustAsync> newTwinRustAsync(
          {required String name, required int age}) =>
      RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinRustAsyncStructForJsonSerializableTwinRustAsyncNewTwinRustAsync(
              name: name, age: age);

  factory StructForJsonSerializableTwinRustAsync.fromJson(
          Map<String, dynamic> json) =>
      _$StructForJsonSerializableTwinRustAsyncFromJson(json);
}
