// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json_serializable.freezed.dart';
part 'json_serializable.g.dart';

@freezed
class StructForJsonSerializableTwinNormal
    with _$StructForJsonSerializableTwinNormal {
  const StructForJsonSerializableTwinNormal._();
  const factory StructForJsonSerializableTwinNormal({
    required String name,
    required int age,
  }) = _StructForJsonSerializableTwinNormal;
  Future<String> detailsTwinNormal() => RustLib.instance.api
          .crateApiJsonSerializableStructForJsonSerializableTwinNormalDetailsTwinNormal(
        that: this,
      );

  static Future<StructForJsonSerializableTwinNormal> newTwinNormal(
          {required String name, required int age}) =>
      RustLib.instance.api
          .crateApiJsonSerializableStructForJsonSerializableTwinNormalNewTwinNormal(
              name: name, age: age);

  factory StructForJsonSerializableTwinNormal.fromJson(
          Map<String, dynamic> json) =>
      _$StructForJsonSerializableTwinNormalFromJson(json);
}
