// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json_serializable_twin_sse.freezed.dart';
part 'json_serializable_twin_sse.g.dart';

@freezed
class StructForJsonSerializableTwinSse with _$StructForJsonSerializableTwinSse {
  const StructForJsonSerializableTwinSse._();
  const factory StructForJsonSerializableTwinSse({
    required String name,
    required int age,
  }) = _StructForJsonSerializableTwinSse;
  Future<String> detailsTwinSse() => RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinSseStructForJsonSerializableTwinSseDetailsTwinSse(
        that: this,
      );

  static Future<StructForJsonSerializableTwinSse> newTwinSse(
          {required String name, required int age}) =>
      RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinSseStructForJsonSerializableTwinSseNewTwinSse(
              name: name, age: age);

  factory StructForJsonSerializableTwinSse.fromJson(
          Map<String, dynamic> json) =>
      _$StructForJsonSerializableTwinSseFromJson(json);
}
