// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json_serializable_twin_sync_sse.freezed.dart';
part 'json_serializable_twin_sync_sse.g.dart';

@freezed
class StructForJsonSerializableTwinSyncSse
    with _$StructForJsonSerializableTwinSyncSse {
  const StructForJsonSerializableTwinSyncSse._();
  const factory StructForJsonSerializableTwinSyncSse({
    required String name,
    required int age,
  }) = _StructForJsonSerializableTwinSyncSse;
  String detailsTwinSyncSse() => RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinSyncSseStructForJsonSerializableTwinSyncSseDetailsTwinSyncSse(
        that: this,
      );

  static StructForJsonSerializableTwinSyncSse newTwinSyncSse(
          {required String name, required int age}) =>
      RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinSyncSseStructForJsonSerializableTwinSyncSseNewTwinSyncSse(
              name: name, age: age);

  factory StructForJsonSerializableTwinSyncSse.fromJson(
          Map<String, dynamic> json) =>
      _$StructForJsonSerializableTwinSyncSseFromJson(json);
}
