// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json_serializable_twin_rust_async_sse.freezed.dart';
part 'json_serializable_twin_rust_async_sse.g.dart';

@freezed
class StructForJsonSerializableTwinRustAsyncSse
    with _$StructForJsonSerializableTwinRustAsyncSse {
  const StructForJsonSerializableTwinRustAsyncSse._();
  const factory StructForJsonSerializableTwinRustAsyncSse({
    required String name,
    required int age,
  }) = _StructForJsonSerializableTwinRustAsyncSse;
  Future<String> detailsTwinRustAsyncSse() => RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinRustAsyncSseStructForJsonSerializableTwinRustAsyncSseDetailsTwinRustAsyncSse(
        that: this,
      );

  static Future<StructForJsonSerializableTwinRustAsyncSse> newTwinRustAsyncSse(
          {required String name, required int age}) =>
      RustLib.instance.api
          .crateApiPseudoManualJsonSerializableTwinRustAsyncSseStructForJsonSerializableTwinRustAsyncSseNewTwinRustAsyncSse(
              name: name, age: age);

  factory StructForJsonSerializableTwinRustAsyncSse.fromJson(
          Map<String, dynamic> json) =>
      _$StructForJsonSerializableTwinRustAsyncSseFromJson(json);
}
